package proyecto;

public enum Estado {
	PARALIZADO, QUEMADO, ENVENENADO, GRAVEMENTE_ENVENENADO, DORMIDO, SOMNOLIENTO,
	CONGELADO, HELADO,POKERUS, CONFUSO, ENAMORADO, ATRAPADO, MALDITO, DRENADORAS,
	CANTO_MORTAL, CENTRO_DE_ATENCION, AMEDRENTADO, DEBILITADO
}
