package model;

public enum Estado {
	PARALIZADO, QUEMADO, ENVENENADO, GRAVEMENTE_ENVENENADO, DORMIDO, SOMNOLIENTO,
	CONGELADO, HELADO,POKERUS, CONFUSO, ENAMORADO, ATRAPADO, MALDITO, DRENADORAS,
	CANTO_MORTAL, CENTRO_DE_ATENCION, AMEDRENTADO, DEBILITADO
}
// ESTADOS FINALMENTE NO UTILIZADOS: HELADO, POKERUS, MALDITO, CANTO_MORTAL, CENTRO_DE_ATENCION, AMEDRENTADO